domain: dev.bigbang.mil

# Uncomment the following settings if using the AWS RKE2 terraform setup
# istio:
#   ingressGateways:
#     public-ingressgateway:
#       type: "NodePort"
#       nodePortBase: 30000

flux:
  interval: 2m
  rollback:
    cleanupOnFail: false

kiali:
  enabled: false

istio:
  enabled: true

istioOperator:
  enabled: true

monitoring:
  enabled: true
  values:
    prometheus:
      prometheusSpec:
        resources:
          requests:
            cpu: 200m
            memory: 1Gi

loki:
  enabled: true
  strategy: scalable
  values:
    minio:
      enabled: true
    write:
      replicas: 1
      persistence:
        size: 2Gi
      resources:
        limits:
          cpu: 200m
          memory: 400Mi
        requests:
          cpu: 200m
          memory: 400Mi
    read:
      replicas: 1
      persistence:
        size: 2Gi
      resources:
        limits:
          cpu: 200m
          memory: 400Mi
        requests:
          cpu: 200m
          memory: 400Mi

promtail:
  enabled: true

kyverno:
  enabled: true

kyvernoPolicies:
  enabled: true
  values:
    exclude:
      any:
      - resources:
          namespaces:
          - istio-system
          - kube-system
          names:
          - svclb-*
    policies:
        disallow-image-tags:
          enabled: true
          validationFailureAction: Audit
          parameters:
            disallow:
            - latest

neuvector:
  enabled: true
  values:
    k3s:
      enabled: true

addons:
  metricsServer:
    enabled: auto

  minioOperator:
    enabled: true # Minio Operator is required for Loki in default core

