configMapGenerator:
  - behavior: merge
    files:
      - values.yaml=configmap.yaml
    name: environment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/
## Comment out the next two lines below if a secrets.enc.yaml is created in this directory
# patches:
# - path: secrets.enc.yaml

