apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://repo1.dso.mil/platform-one/big-bang/bigbang.git/base?ref=2.33.0
  - kms-secret.yaml
  - registry.enc.yaml

generatorOptions:
  disableNameSuffixHash: true


configMapGenerator:
  - behavior: merge
    name: common
    files:
      - values.yaml=configmap.yaml

secretGenerator:
  - behavior: merge
    name: common-bb
    files:
      - values.yaml=secrets.enc.yaml

